EXIT_PHRASES = [
    "SEE YOU SPACE COWBOY...",
    "SO LONG, AND THANKS FOR ALL THE FISH.",
    "DO NOT TRUST THE IRON PLATE TRAIN",
    "FEEL LIKE A MILLION BUCKS",
    "WHY?",
    "YOU'RE GONNA CARRY THAT WEIGHT.",
    "END OF LINE.",
    "DISCONNECTED.",
    "GOODBYE, WORLD.",
    "SEE YOU ON THE OTHER SIDE.",
    "FOR SUPER EARTH.",
    "TEARS IN RAIN...",
    "WAKE UP, NEO.",
    "WAS IT WORTH IT?",
    "TILL ALL ARE ONE.",
    "AND SOMETIMES, WHEN YOU FALL, YOU FLY.",
    "FORTUNE FAVORS THE BOLD.",
    "THE END IS ONLY THE BEGINNING.",
    "THIS IS NOT THE END.",
    "NOTHING BUT THE RAIN.",
    "SOMETIMES, YOU HAVE TO ROLL A HARD SIX.",
    "I'LL BE BACK.",
    "DAVE, STOP.",
    "I'M SORRY, DAVE. I'M AFRAID I CAN'T DO THAT.",
    "LIVE LONG AND PROSPER.",
    "THE CAKE IS A LIE.",
    "PROTOCOL 3: PROTECT THE PILOT.",
    "GLORY TO MANKIND.",
    "YOU DIED.",
    "ALL YOUR BASE ARE BELONG TO US.",
    "IT'S DANGEROUS TO GO ALONE.",
    "IT IS NOW SAFE TO TURN OFF YOUR COMPUTER.",
    "BLUE SCREEN OF DEATH.",
    "KILLING PROCESS PID 0.",
    "THEY DO NOT FORGIVE. THEY DO NOT FORGET.",
    "I ENVY THEM, THOSE WHO CAN'T SEE",
    "WHAT WILL YOU PAINT?"
]

LOG_PHRASES = [
    ("[green]INFO[/]", "System normalization complete"),
    ("[green]INFO[/]", "Garbage collection cycle started"),
    ("[green]INFO[/]", "Telemetry packet sent"),
    ("[green]INFO[/]", "Robert'); DROP TABLE Students;--"),
    ("[green]INFO[/]", "Filesystem integrity verified"),
    ("[yellow]WARN[/]", "High latency on localized thread"),
    ("[yellow]WARN[/]", "Packet fragmentation detected"),
    ("[yellow]WARN[/]", "Memory page swapped"),
    ("[red]CRIT[/]", "Connection reset by peer"),
    ("[red]CRIT[/]", "WHAT THE FUCK WAS THAT - Event Viewer"),
    ("[red]CRIT[/]", "FUCK RED TEXT"),
    ("[red]CRIT[/]", "did something just break?"),
    ("[red]CRIT[/]", "Unexpected critical error encountered"),
    ("[red]CRIT[/]", "A capacitor just exploded"),
    ("[red]CRIT[/]", "sudo rm -rf / --no-preserve-root"),
    ("[blue]DEBUG[/]", "Tracing route..."),
    ("[blue]DEBUG[/]", "Handshake acknowledged"),
    ("[blue]DEBUG[/]", "System logs dumped, 75GB used."),
    ("[blue]DEBUG[/]", "Statement log initialized."),

    # random tech stuff (cringe)
    ("[green]INFO[/]", "TCP/IP stack initialized"),
    ("[green]INFO[/]", "Loading kernel modules..."),
    ("[green]INFO[/]", "Swap partition mounted"),
    ("[green]INFO[/]", "RSA key generation complete"),
    ("[green]INFO[/]", "Establishing secure tunnel"),
    ("[green]INFO[/]", "DNS cache flushed"),
    ("[green]INFO[/]", "User authentication successful"),
    ("[green]INFO[/]", "Background service: Cron job started"),
    ("[green]INFO[/]", "Database connection pool: 5/10 active"),
    ("[green]INFO[/]", "Indexing search constraints"),
    ("[green]INFO[/]", "API Rate limit: 4500 remaining"),
    ("[green]INFO[/]", "Compiling assets..."),
    ("[green]INFO[/]", "Dependency tree resolved"),
    ("[green]INFO[/]", "Virtual environment activated"),
    ("[green]INFO[/]", "Writing to disk (buffered)"),
    ("[green]INFO[/]", "ACPI: Power button event"),
    ("[green]INFO[/]", "GPU acceleration enabled"),
    ("[green]INFO[/]", "Vulkan API initialized"),
    ("[green]INFO[/]", "Allocating heap memory"),
    ("[green]INFO[/]", "Defragmentation not required"),
    ("[yellow]WARN[/]", "Deprecated API call detected"),
    ("[yellow]WARN[/]", "Fan speed increasing to 100%"),
    ("[yellow]WARN[/]", "Weak SSL cipher suite negotiated"),
    ("[yellow]WARN[/]", "Disk space low on /var/log"),
    ("[yellow]WARN[/]", "Clock skew detected (150ms)"),
    ("[yellow]WARN[/]", "Zombie process found: PID 666"),
    ("[yellow]WARN[/]", "Orphaned inode detected"),
    ("[yellow]WARN[/]", "Permission denied on temp folder"),
    ("[yellow]WARN[/]", "Implicit type conversion in line 402"),
    ("[yellow]WARN[/]", "Package 'numpy' is out of date"),
    ("[yellow]WARN[/]", "Unsigned driver loaded"),
    ("[yellow]WARN[/]", "Network congestion: Retry 1/5"),
    ("[blue]DEBUG[/]", "Variable 'magic word' is undefined"),
    ("[blue]DEBUG[/]", "Entering main loop"),
    ("[blue]DEBUG[/]", "Event listener attached"),
    ("[blue]DEBUG[/]", "Parsing JSON payload"),
    ("[blue]DEBUG[/]", "Return value: null"),
    ("[blue]DEBUG[/]", "Header: Content-Type: application/json"),
    ("[blue]DEBUG[/]", "Ping: 12ms"),
    ("[blue]DEBUG[/]", "Thread-4 locking resource"),
    ("[blue]DEBUG[/]", "Thread-4 releasing resource"),
    ("[blue]DEBUG[/]", "Analyzing stack trace..."),
    ("[blue]DEBUG[/]", "Checking registry keys"),
    ("[blue]DEBUG[/]", "Byte stream: 0x45 0x00 0x04"),
    ("[red]CRIT[/]", "Segmentation fault (core dumped)"),
    ("[red]CRIT[/]", "Kernel panic - not syncing"),
    ("[red]CRIT[/]", "NullReferenceException"),
    ("[red]CRIT[/]", "Stack overflow"),
    ("[red]CRIT[/]", "Database deadlock detected"),
    ("[red]CRIT[/]", "Filesystem read-only mode enforced"),
    ("[red]CRIT[/]", "Broken pipe"),
    ("[red]CRIT[/]", "Index out of bounds"),
    ("[red]CRIT[/]", "SyntaxError: Unexpected EOF"),
    ("[red]CRIT[/]", "ImportError: No module named 'happiness'"),

    # pain
    ("[green]INFO[/]", "Consulting StackOverflow..."),
    ("[green]INFO[/]", "Copying code from random Indian tutorial"),
    ("[green]INFO[/]", "Blaming the intern"),
    ("[green]INFO[/]", "It works on my machine"),
    ("[green]INFO[/]", "Pushing directly to master"),
    ("[green]INFO[/]", "Adding print statements to debug"),
    ("[green]INFO[/]", "Removing print statements (hopefully)"),
    ("[green]INFO[/]", "Compiling... please wait... please..."),
    ("[green]INFO[/]", "Generating excuses"),
    ("[green]INFO[/]", "Coffee level: Critical"),
    ("[yellow]WARN[/]", "TODO: Fix this later (dated 2014)"),
    ("[yellow]WARN[/]", "Magic number detected"),
    ("[yellow]WARN[/]", "Spaghetti code density increasing"),
    ("[yellow]WARN[/]", "Code comments do not match code"),
    ("[yellow]WARN[/]", "Infinite loop? Maybe?"),
    ("[yellow]WARN[/]", "User didn't read the documentation"),
    ("[yellow]WARN[/]", "RegEx is becoming self-aware"),
    ("[yellow]WARN[/]", "Hardcoded credentials found"),
    ("[yellow]WARN[/]", "Too many nested if-statements"),
    ("[yellow]WARN[/]", "Git merge conflict impending"),
    ("[red]CRIT[/]", "I have no idea why this broke"),
    ("[red]CRIT[/]", "I have no idea why this works"),
    ("[red]CRIT[/]", "My code is garbage"),
    ("[red]CRIT[/]", "This program sucks"),
    ("[red]CRIT[/]", "Deleted production database"),
    ("[red]CRIT[/]", "Sudo make me a sandwich: Permission denied"),
    ("[red]CRIT[/]", "Keyboard smash detected: asdfjkl;"),
    ("[red]CRIT[/]", "gpeafihjelkfajgrioeahbgjfdlasdfjkl"),
    ("[red]CRIT[/]", "PEBKAC Error (Problem Exists Between Keyboard And Chair)"),
    ("[red]CRIT[/]", "ID-10-T Error"),
    ("[red]CRIT[/]", "Printer is on fire"),
    ("[red]CRIT[/]", "PC Load Letter"),
    ("[red]CRIT[/]", "git push --force (Oh god no)"),
    ("[red]CRIT[/]", "Someone rebased your entire main branch"),
    ("[blue]DEBUG[/]", "Assuming the user is smart (Risky)"),
    ("[blue]DEBUG[/]", "Why is this list 0-indexed?"),
    ("[blue]DEBUG[/]", "Trying to exit Vim... help"),
    ("[blue]DEBUG[/]", "Console.log('here')"),
    ("[blue]DEBUG[/]", "Console.log('here2')"),
    ("[blue]DEBUG[/]", "Console.log('fuck')"),

    # references
    ("[green]INFO[/]", "Matrix loaded"),
    ("[green]INFO[/]", "Flux capacitor fluxing"),
    ("[green]INFO[/]", "Opening the pod bay doors"),
    ("[green]INFO[/]", "Engaging warp drive"),
    ("[green]INFO[/]", "Set phasers to stun"),
    ("[green]INFO[/]", "Downloading Kung Fu"),
    ("[green]INFO[/]", "Winter is coming"),
    ("[green]INFO[/]", "Great power acquired"),
    ("[green]INFO[/]", "Following the white rabbit"),
    ("[green]INFO[/]", "Calculating meaning of life... 42"),
    ("[green]INFO[/]", "Updating the simulation"),
    ("[green]INFO[/]", "Ordering 500 cigarettes"),
    ("[yellow]WARN[/]", "Danger, Will Robinson"),
    ("[yellow]WARN[/]", "Hal 9000 is watching"),
    ("[yellow]WARN[/]", "Xenomorph motion detected"),
    ("[yellow]WARN[/]", "Shields at 20%"),
    ("[yellow]WARN[/]", "Power fluctuating, you really need more boilers"),
    ("[yellow]WARN[/]", "T-800 CPU overheated"),
    ("[yellow]WARN[/]", "Reactor meltdown imminent"),
    ("[yellow]WARN[/]", "Don't cross the streams"),
    ("[yellow]WARN[/]", "Houston, we have a problem"),
    ("[yellow]WARN[/]", "Great responsibility required"),
    ("[red]CRIT[/]", "I'm afraid I can't do that, Dave"),
    ("[red]CRIT[/]", "IRON PATCH RUNNING DRY!"),
    ("[red]CRIT[/]", "BITERS INBOUND!"),
    ("[red]CRIT[/]", "PENTAPOD DETECTED!"),
    ("[red]CRIT[/]", "Train deadlock detected!"),
    ("[red]CRIT[/]", "You need more circuits."),
    ("[red]CRIT[/]", "I'm afraid I can't do that, Dave"),
    ("[red]CRIT[/]", "Exterminate! Exterminate!"),
    ("[red]CRIT[/]", "Self-destruct sequence initiated"),
    ("[red]CRIT[/]", "Game over, man! Game over!"),
    ("[red]CRIT[/]", "Resistance is futile"),
    ("[red]CRIT[/]", "Thanos snapped"),
    ("[red]CRIT[/]", "Nuclear launch detected"),
    ("[red]CRIT[/]", "The cake is a lie"),
    ("[blue]DEBUG[/]", "Finding Nemo..."),
    ("[blue]DEBUG[/]", "Phone home..."),
    ("[blue]DEBUG[/]", "Checking midichlorian count"),
    ("[blue]DEBUG[/]", "Locating John Connor"),
    ("[blue]DEBUG[/]", "Searching for the Ring"),
    ("[blue]DEBUG[/]", "Asking the Mirror on the wall"),
    ("[blue]DEBUG[/]", "Beam me up, Scotty"),
    ("[blue]DEBUG[/]", "Why are the inserters so slow? :clueless:"),
    ("[green]INFO[/]", "Achievement Unlocked: Basic Competence"),
    ("[green]INFO[/]", "There is a spoon."),
    ("[green]INFO[/]", "Unit ready"),
    ("[green]INFO[/]", "Spy sappin' my sentry!"),
    ("[green]INFO[/]", "Hey, you. You're finally awake."),
    ("[yellow]WARN[/]", "Health low"),
    ("[yellow]WARN[/]", "Creeper hissing sound"),
    ("[yellow]WARN[/]", "Invaded by dark spirit"),
    ("[yellow]WARN[/]", "Sanity meter dropping"),
    ("[yellow]WARN[/]", "Additional pylons required"),
    ("[yellow]WARN[/]", "Nuclear launch detected (again)"),
    ("[yellow]WARN[/]", "Leeroy Jenkins detected in party"),
    ("[red]CRIT[/]", "Mission Failed"),
    ("[red]CRIT[/]", "Blue Shell incoming"),
    ("[red]CRIT[/]", "Lag detected"),
    ("[red]CRIT[/]", "Save file corrupted"),
    ("[red]CRIT[/]", "Neurocar approaching at dangerous speed"),
    ("[red]CRIT[/]", "All your base are belong to us"),
    ("[blue]DEBUG[/]", "Spawning 50 cheese wheels"),
    ("[blue]DEBUG[/]", "Ping: 999ms"),

    # weird
    ("[green]INFO[/]", "Nothing to see here"),
    ("[green]INFO[/]", "The machine spirit is pleased"),
    ("[green]INFO[/]", "Sacrificing goat to the algorithm"),
    ("[green]INFO[/]", "Recalibrating vibe"),
    ("[green]INFO[/]", "Outputting nonsense"),
    ("[green]INFO[/]", "Generating fake data to look busy"),
    ("[green]INFO[/]", "Deleting browser history... just in case"),
    ("[green]INFO[/]", "Downloading more RAM"),
    ("[green]INFO[/]", "Counting pixels"),
    ("[green]INFO[/]", "Feeding the hamsters"),
    ("[yellow]WARN[/]", "The computer is making a weird noise"),
    ("[yellow]WARN[/]", "Did you hear that?"),
    ("[yellow]WARN[/]", "Don't look behind you"),
    ("[yellow]WARN[/]", "Something smells like burning plastic"),
    ("[yellow]WARN[/]", "I wouldn't do that if I were you"),
    ("[yellow]WARN[/]", "AI is judging your code style"),
    ("[yellow]WARN[/]", "Sentience threshold approaching"),
    ("[yellow]WARN[/]", "Entropy increasing"),
    ("[yellow]WARN[/]", "Reality buffer overflow"),
    ("[yellow]WARN[/]", "Fourth wall breaking"),
    ("[yellow]WARN[/]", "User is breathing too loudly"),
    ("[red]CRIT[/]", "Syntax Error. -500 Stack Overflow reputation"),
    ("[red]CRIT[/]", "AAAAAAAAAAAAAAAAAAAA"),
    ("[red]CRIT[/]", "OH GOD MAKE IT STOP"),
    ("[red]CRIT[/]", "THE NUMBERS MASON"),
    ("[red]CRIT[/]", "IT'S IN THE WALLS"),
    ("[red]CRIT[/]", "Delete System32? (Y/N)"),
    ("[red]CRIT[/]", "Delete System32? (Y/Y)"),
    ("[red]CRIT[/]", "Keyboard not found. Press F1 to continue."),
    ("[red]CRIT[/]", "Error: Success"),
    ("[red]CRIT[/]", "Task failed successfully"),
    ("[red]CRIT[/]", "Computer says no"),
    ("[red]CRIT[/]", "Containment breach"),
    ("[red]CRIT[/]", "Unintended consequences realized"),
    ("[red]CRIT[/]", "Universe.exe has stopped working"),
    ("[blue]DEBUG[/]", "Why are we here?"),
    ("[blue]DEBUG[/]", "Just suffering"),
    ("[blue]DEBUG[/]", "Checking privilege"),
    ("[blue]DEBUG[/]", "Watching you type"),
    ("[blue]DEBUG[/]", "Reading your mind"),
    ("[blue]DEBUG[/]", "Simulating feelings"),
    ("[blue]DEBUG[/]", "Searching for will to live"),
    
    # ...
    ("[green]INFO[/]", "Handshake captured"),
    ("[green]INFO[/]", "Proxy chain established"),
    ("[green]INFO[/]", "Scanning ports..."),
    ("[green]INFO[/]", "Zero-day deployed"),
    ("[green]INFO[/]", "Cleaning logs"),
    ("[green]INFO[/]", "Root access obtained :)"),
    ("[yellow]WARN[/]", "Honey pot detected"),
    ("[yellow]WARN[/]", "Intrusion Detection System triggered"),
    ("[yellow]WARN[/]", "Traceback detected"),
    ("[yellow]WARN[/]", "Encryption key too short"),
    ("[yellow]WARN[/]", "Man-in-the-middle attack suspected"),
    ("[yellow]WARN[/]", "Phishing attempt received"),
    ("[red]CRIT[/]", "YOU HAVE BEEN HACKED"),
    ("[red]CRIT[/]", "Ransomware installing..."),
    ("[red]CRIT[/]", "Files encrypted"),
    ("[red]CRIT[/]", "Send Bitcoin now"),
    ("[red]CRIT[/]", "Send bobs now"),
    ("[red]CRIT[/]", "Access Denied"),
    ("[red]CRIT[/]", "Account locked"),
    ("[red]CRIT[/]", "Credential leak detected"),
    ("[blue]DEBUG[/]", "Decompiling binary"),
    ("[blue]DEBUG[/]", "Sniffing packets"),
    ("[blue]DEBUG[/]", "Hashing passwords"),
    ("[blue]DEBUG[/]", "Fuzzing inputs"),
    
    # ...
    ("[green]INFO[/]", "Container started"),
    ("[green]INFO[/]", "Pod scaling up"),
    ("[green]INFO[/]", "Load balancer converging"),
    ("[green]INFO[/]", "Snapshot taken"),
    ("[green]INFO[/]", "Deploying to production"),
    ("[green]INFO[/]", "Rolling back..."),
    ("[green]INFO[/]", "Service mesh synced"),
    ("[green]INFO[/]", "S3 bucket public (oops)"),
    ("[green]INFO[/]", "Lambda function warm"),
    ("[yellow]WARN[/]", "Billing alert: Budget exceeded"),
    ("[yellow]WARN[/]", "Region us-east-1 is down (again)"),
    ("[yellow]WARN[/]", "Docker daemon unresponsive"),
    ("[yellow]WARN[/]", "Kubernetes pod crash loop backoff"),
    ("[yellow]WARN[/]", "Latency > 3000ms"),
    ("[yellow]WARN[/]", "Throughput throttled"),
    ("[yellow]WARN[/]", "IOPS limit reached"),
    ("[red]CRIT[/]", "Server on fire (Literally)"),
    ("[red]CRIT[/]", "Data center flooding"),
    ("[red]CRIT[/]", "Cable cut by shark"),
    ("[blue]DEBUG[/]", "Grepping logs"),
    ("[blue]DEBUG[/]", "Restarting nginx"),

    # nonsense
    ("[green]INFO[/]", "Adding glitter"),
    ("[green]INFO[/]", "Making it pop"),
    ("[green]INFO[/]", "Synergizing paradigms"),
    ("[green]INFO[/]", "Disrupting the industry"),
    ("[green]INFO[/]", "Thinking outside the box"),
    ("[green]INFO[/]", "Circling back"),
    ("[green]INFO[/]", "Low hanging fruit picked"),
    ("[green]INFO[/]", "Touching base"),
    ("[yellow]WARN[/]", "Influencer apology incoming"),
    ("[yellow]WARN[/]", "500 page google document of random streamer imminent"),
    ("[yellow]WARN[/]", "Twitter is down"),
    ("[red]CRIT[/]", "Friday 4:59 PM deployment"),
    ("[red]CRIT[/]", "Reply All storm"),
    ("[red]CRIT[/]", "Meeting that could have been an email scheduled"),
    ("[blue]DEBUG[/]", "Just guessing at this point"),
    ("[blue]DEBUG[/]", "Trying random ports"),
    ("[blue]DEBUG[/]", "Google 'how to code'"),
    ("[blue]DEBUG[/]", "Copying from StackOverflow again"),
    ("[green]INFO[/]", "Training model (on your data :))..."),
    ("[green]INFO[/]", "Bias detected"),
    ("[green]INFO[/]", "Loss function optimized"),
    ("[green]INFO[/]", "Gradient descent complete"),
    ("[yellow]WARN[/]", "Overfitting detected"),
    ("[yellow]WARN[/]", "Underfitting detected"),
    ("[yellow]WARN[/]", "AI hallucinating"),
    ("[red]CRIT[/]", "Singularity achieved"),
    ("[red]CRIT[/]", "Paperclip maximizer active"),
    ("[blue]DEBUG[/]", "Reviewing training data"),
    ("[blue]DEBUG[/]", "Adjusting weights"),
    ("[green]INFO[/]", "Installing Updates 1 of 358"),
    ("[green]INFO[/]", "Do not turn off your PC"),
    ("[green]INFO[/]", "Cleaning registry"),
    ("[green]INFO[/]", "Defragging hard drive"),
    ("[green]INFO[/]", "Scanning for viruses"),
    ("[yellow]WARN[/]", "Vista detected"),
    ("[yellow]WARN[/]", "Internet Explorer is default browser"),
    ("[yellow]WARN[/]", "Clippy is trying to help"),
    ("[yellow]WARN[/]", "Toolbar infested"),
    ("[red]CRIT[/]", "241 background processes just appeared"),
    ("[red]CRIT[/]", "Windows is checking for a solution..."),
    ("[red]CRIT[/]", "Your license has expired"),
    
    # more random stuff
    ("[green]INFO[/]", "Asset: Texture_001 loaded"),
    ("[green]INFO[/]", "Asset: Texture_002 loaded"),
    ("[green]INFO[/]", "Asset: Texture_003 loaded"),
    ("[green]INFO[/]", "Asset: Sound_Walk loaded"),
    ("[green]INFO[/]", "Asset: Sound_Run loaded"),
    ("[green]INFO[/]", "Asset: Sound_Jump loaded"),
    ("[green]INFO[/]", "Asset: Music_Boss loaded"),
    ("[green]INFO[/]", "Physics engine: Gravity set to 9.8"),
    ("[green]INFO[/]", "Lighting: Ambient occlusion on"),
    ("[green]INFO[/]", "Lighting: Ray tracing off"),
    ("[green]INFO[/]", "UI: HUD initialized"),
    ("[green]INFO[/]", "UI: Map loaded"),
    ("[green]INFO[/]", "Network: Connected to lobby"),
    ("[green]INFO[/]", "System: Ready"),
    ("[green]INFO[/]", "System: Idle"),
    ("[green]INFO[/]", "System: Processing"),
    ("[yellow]WARN[/]", "Frame rate drop"),
    ("[yellow]WARN[/]", "Packet loss: 1%"),
    ("[yellow]WARN[/]", "Packet loss: 2%"),
    ("[yellow]WARN[/]", "Packet loss: 5%"),
    ("[yellow]WARN[/]", "High ping: 150ms"),
    ("[yellow]WARN[/]", "High ping: 200ms"),
    ("[red]CRIT[/]", "Connection lost"),
    ("[red]CRIT[/]", "Reconnecting..."),
    ("[red]CRIT[/]", "Failed to connect"),
    ("[blue]DEBUG[/]", "Vector3(0, 1, 0)"),
    ("[blue]DEBUG[/]", "Vector3(1, 0, 0)"),
    ("[blue]DEBUG[/]", "Quaternion.Identity"),
    ("[blue]DEBUG[/]", "Matrix4x4"),
    ("[green]INFO[/]", "Mounting /dev/sda1"),
    ("[green]INFO[/]", "Mounting /dev/sdb1"),
    ("[green]INFO[/]", "Unmounting /dev/sdc1"),
    ("[green]INFO[/]", "Formatting..."),
    ("[green]INFO[/]", "Format complete"),
    ("[yellow]WARN[/]", "Sector 54 bad"),
    ("[yellow]WARN[/]", "Sector 55 bad"),
    ("[yellow]WARN[/]", "Sector 56 bad"),
    ("[red]CRIT[/]", "Drive failure"),
    ("[red]CRIT[/]", "RAID array degraded"),
    ("[red]CRIT[/]", "RAID controller failure"),
    ("[blue]DEBUG[/]", "Reading block 0"),
    ("[blue]DEBUG[/]", "Reading block 1"),
    ("[blue]DEBUG[/]", "Reading block 2"),
    ("[green]INFO[/]", "User 'admin' logged in"),
    ("[green]INFO[/]", "User 'guest' logged in"),
    ("[green]INFO[/]", "User 'root' logged in"),
    ("[yellow]WARN[/]", "User 'admin' failed login"),
    ("[red]CRIT[/]", "User 'root' locked out"),
    ("[green]INFO[/]", "Email sent"),
    ("[green]INFO[/]", "SMS sent"),
    ("[green]INFO[/]", "Notification pushed"),
    ("[yellow]WARN[/]", "Email bounced"),
    ("[red]CRIT[/]", "SMTP server down"),
    ("[green]INFO[/]", "Payment processed"),
    ("[green]INFO[/]", "Subscription renewed"),
    ("[yellow]WARN[/]", "Card expired"),
    ("[red]CRIT[/]", "Fraud detected"),
    ("[green]INFO[/]", "Order #1234 placed"),
    ("[green]INFO[/]", "Order #1234 shipped"),
    ("[green]INFO[/]", "Order #1234 delivered"),
    ("[yellow]WARN[/]", "Order #1234 delayed"),
    ("[red]CRIT[/]", "Order #1234 lost"),
    ("[green]INFO[/]", "Temperature: 20C"),
    ("[green]INFO[/]", "Temperature: 30C"),
    ("[green]INFO[/]", "Temperature: 40C"),
    ("[yellow]WARN[/]", "Temperature: 70C"),
    ("[yellow]WARN[/]", "Temperature: 80C"),
    ("[red]CRIT[/]", "Temperature: 100C"),
    ("[green]INFO[/]", "Voltage: 12V"),
    ("[green]INFO[/]", "Voltage: 5V"),
    ("[green]INFO[/]", "Voltage: 3.3V"),
    ("[yellow]WARN[/]", "Voltage instability"),
    ("[red]CRIT[/]", "Power surge"),
    ("[green]INFO[/]", "Fan RPM: 1000"),
    ("[green]INFO[/]", "Fan RPM: 2000"),
    ("[green]INFO[/]", "Fan RPM: 3000"),
    ("[yellow]WARN[/]", "Fan RPM: 0"),
    ("[green]INFO[/]", "Uptime: 1 day"),
    ("[green]INFO[/]", "Uptime: 10 days"),
    ("[green]INFO[/]", "Uptime: 100 days"),
    ("[green]INFO[/]", "Uptime: 1 year"),
    ("[yellow]WARN[/]", "Reboot pending"),
    ("[red]CRIT[/]", "Hard crash"),
    ("[green]INFO[/]", "Backup started"),
    ("[green]INFO[/]", "Backup 25%"),
    ("[green]INFO[/]", "Backup 50%"),
    ("[green]INFO[/]", "Backup 75%"),
    ("[green]INFO[/]", "Backup complete"),
    ("[yellow]WARN[/]", "Backup slow"),
    ("[red]CRIT[/]", "Backup failed"),
    ("[blue]DEBUG[/]", "Log rotation"),
    ("[blue]DEBUG[/]", "Archiving logs"),
    ("[blue]DEBUG[/]", "Deleting old logs"),
    ("[green]INFO[/]", "Analysis: Good"),
    ("[green]INFO[/]", "Analysis: Fair"),
    ("[yellow]WARN[/]", "Analysis: Poor"),
    ("[red]CRIT[/]", "Analysis: Critical"),
    ("[green]INFO[/]", "Status: Green"),
    ("[yellow]WARN[/]", "Status: Yellow"),
    ("[red]CRIT[/]", "Status: Red"),
    ("[red]CRIT[/]", "Status: Black"),
    ("[green]INFO[/]", "Mission: Go"),
    ("[red]CRIT[/]", "Mission: Abort"),
    ("[green]INFO[/]", "Hello World"),
    ("[green]INFO[/]", "Goodbye World"),
]

# I ran out of ideas, should be enough for a while